### ISSUE TITLE
Cookie cutter for project organization

### ISSUE THREAD

**Issue by christopheralex** [UBC-MDS/airpyllution#1]

**Comment by christopheralex** [comment]
Apparently cookie cutter creates the file structure and the next step is to create a github repository with that package.
This is shown in Cookiecutter documentation and our individual assignment 1.

**Comment by mel-liow** [comment]
Oh i see - so we'd have to recreate the repo? I feel like at this point because our project is so small still, it might be fine manually creating the folders? 
I think all we need is:
`/docs` 
 - `requirements.txt`

`/test` 
- `test_air_pollution.py`

`/src`
- `air_pollution.py`

**Comment by christopheralex** [comment]
Cookiecutter provides a nice big structure. Let me see if I can do a workaround.

**Comment by mel-liow** [comment]
Okay cool! we might not need all the files it creates though so if the workaround is too complicated it'll probs be fine to just manually create them

**Comment by christopheralex** [comment]
Closing issue as issue solved in commit 6c46f88df5a37375b94d3bd320a186d645b8aded .
