### ISSUE TITLE
Continuous Integration setup

### ISSUE THREAD

**Issue by mel-liow** [UBC-MDS/airpyllution#41]
- [x] Configure build.yml
- [x] Runs the test suite and style checkers on PRs

**Comment by mel-liow** [comment]
CI build is currently passing: 

<img width="1073" alt="Screenshot 2022-01-25 at 11 14 17" src="https://user-images.githubusercontent.com/40150248/151043707-5045bca0-2c9c-484f-97bf-0d27f42f65cd.png">

Our package isn't coming up on Codecov so haven't been able to add it to CI yet but will look at this end of the week

**Comment by christopheralex** [comment]
Poetry install seems to fail on the latest merge ? Any reasons why ?

**Comment by christopheralex** [comment]
![image](https://user-images.githubusercontent.com/37771404/151633169-18e1d3c9-6d58-4a58-b374-d05acc6dd462.png)
