### ISSUE TITLE
Continuous Deployment setup

### ISSUE THREAD

**Issue by mel-liow** [UBC-MDS/airpyllution#42]
- [ ] Runs test suite and styling
- [ ] Deploys the package to test PyPI when pushed to deployment branch
- [ ] Create deploy.yml file

At time of submission, we expect that your project successfully runs this workflow. This should be evidenced by a green release button on your package repository’s README.

**Comment by mel-liow** [comment]
FYI - i've disabled the `release.yml` workflow for now to just get CI working. You should be able to click 'enable' when you start working on it https://github.com/UBC-MDS/airpyllution/actions/workflows/release.yml

**Comment by christopheralex** [comment]
@mel-liow Doesn't test suite with styling come under CI ?
Also can I just continue with release.yml instead of renaming to deploy.yml ?

**Comment by mel-liow** [comment]
Oh sorry - yes maybe change it to deploy.yml - my bad, i think it's different name from her lecture notes (she says release.yml) 

And yeah i think test suite and styling is done by CI so dw about that - i was just copying it from the milestone 3
