### ISSUE TITLE
Docstring for get_pollution_forecast()

### ISSUE THREAD

**Issue by danfke** [UBC-MDS/airpyllution#7]
Fetches air pollution data for the next 5 days for a specific location. The function returns a time series plot of the predicted pollution levels.

**Comment by danfke** [comment]
API request is done in the following format: `requests.get(
    f'http://api.openweathermap.org/data/2.5/air_pollution/forecast?lat={lat}&lon={lon}&appid={api_key}'
)`

Required arguments: lat, lon, api_key

How do we deal with api_key when it comes to the user?

**Comment by danfke** [comment]
The output for this API call is the same as getAirPollution() but everything after the coords are repeated for the forecasted time periods

**Comment by mel-liow** [comment]
> How do we deal with api_key when it comes to the user?

I think we should make a separate issue to deal with this. We'll probably have them add their key to a config file that gets read in - I can look into it.
